### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by holden** [omniauth/omniauth#460]
I'm having a problem with UTF8 and complex names such as "Joe McÙisnean"

I get the above error when I try to do something like this in my model.  I'm not sure if it's something I'm doing, but I haven't had any related errors on anything except when dealing with Omniauth data.

self.name = omniauth['user_info']['name']

http://stackoverflow.com/questions/7349913/rails-omniauth-and-utf-8-errors

**Comment by f3ndot** [comment]
I am confused as to why this was closed. Am using Rails 4.2.7.1, Ruby 2.0.0, and Omniauth 1.3.1 but occasionally get the error @holden describes above from Google App OAuth callbacks:

```
2016-08-25T14:02:31-04:00 mlapp01 masterlock-unicorn[2665]: FATAL   Encoding::UndefinedConversionError ("\xA9" from ASCII-8BIT to UTF-8):
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `encode'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `to_json'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:57:in `to_json'
  vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
  vendor/bundle/ruby/2.0.0/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:101:in `stringify'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:35:in `encode'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:22:in `encode'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:401:in `dump'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:414:in `serialize'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:527:in `[]='
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:421:in `block in deserialize'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:420:in `tap'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:420:in `deserialize'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:516:in `[]'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:114:in `get_cookie'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:90:in `block in unpacked_cookie_data'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:89:in `unpacked_cookie_data'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:73:in `block in load_session'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:72:in `load_session'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/request/session.rb:180:in `load!'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/request/session.rb:176:in `load_for_write!'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/request/session.rb:109:in `[]='
  vendor/bundle/ruby/2.0.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:201:in `request_call'
  vendor/bundle/ruby/2.0.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:183:in `call!'
  vendor/bundle/ruby/2.0.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
  vendor/bundle/ruby/2.0.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/lograge-0.4.1/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:125:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/timeout.rb:19:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/timeout.rb:19:in `timeout'
  vendor/bundle/ruby/2.0.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:124:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rocket_pants-1.13.0/lib/rocket_pants/cache_middleware.rb:21:in `_call'
  vendor/bundle/ruby/2.0.0/gems/rocket_pants-1.13.0/lib/rocket_pants/cache_middleware.rb:12:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.0.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
  vendor/bundle/ruby/2.0.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:92:in `process_client'
  vendor/bundle/ruby/2.0.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
  vendor/bundle/ruby/2.0.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  vendor/bundle/ruby/2.0.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
  vendor/bundle/ruby/2.0.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:283:in `join'
  vendor/bundle/ruby/2.0.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  bin/unicorn:16:in `load'
  bin/unicorn:16:in `<main>'
``` 

As you can see, nowhere in the stack trace does it hit our app.

Could you provide some insight as to why you closed this ticket? Is there a solution I'm not aware of?

There is some information on the internet [pointing fingers at Omniauth](https://stackoverflow.com/questions/7349913/rails-omniauth-and-utf-8-errors) stating that it incorrectly mucks with encoding.

I appreciate any insight you could give us, thanks @mbleigh.
