### ISSUE TITLE
OmniAuth::AuthHash inherits from Hashie::Mash but doesn't implement options on to_hash

### ISSUE THREAD

**Issue by mikebaldry** [omniauth/omniauth#737]
Hashie::Mash#to_hash takes options argument but AuthHash inherits from this class and overrides to_hash without arguments.

This is causing me an error

```
wrong number of arguments (1 for 0)

omniauth (1.2.1) lib/omniauth/auth_hash.rb:47:in `to_hash'
hashie (2.1.0) lib/hashie/hash.rb:22:in `block in to_hash'
hashie (2.1.0) lib/hashie/hash.rb:13:in `each'
hashie (2.1.0) lib/hashie/hash.rb:13:in `to_hash'
hashie (2.1.0) lib/hashie/hash.rb:30:in `to_json'
/Users/michaelbaldry/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:2
```

This commit to hashie seems to have caused it:

https://github.com/intridea/hashie/commit/a798eba1458ff8b48760e190e92d94ad8e87de34

**Comment by tmilewski** [comment]
Closing per Hashie updates.
