### ISSUE TITLE
can't modify frozen Array

### ISSUE THREAD

**Issue by aspiers** [omniauth/omniauth#751]
I have the following `config/initializers/omniauth.rb`:

```
module MyApp
  class Application
    module OmniAuth
      def self.settings
        @@settings
      end

      @@yml_path = Rails.root.join("config", "omniauth", Rails.env + ".yml")
      @@settings = YAML.load(IO.read(@@yml_path))

      Rails.application.config.middleware.use ::OmniAuth::Builder do
        MyApp::Application::OmniAuth.settings.each do |service, secrets|
          provider service.to_sym, secrets['API_key'], secrets['app_secret']
        end
      end
    end
  end
end
```

but then this happens:

```
$ spring rake -T
Warning: You're using Rubygems 1.8.25 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
rake aborted!
can't modify frozen Array
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/actionpack-4.0.5/lib/action_dispatch/middleware/stack.rb:112:in `push'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/actionpack-4.0.5/lib/action_dispatch/middleware/stack.rb:112:in `use'
/home/adam/rails/myapp/config/initializers/omniauth.rb:11:in `<module:OmniAuth>'
/home/adam/rails/myapp/config/initializers/omniauth.rb:3:in `<class:Application>'
/home/adam/rails/myapp/config/initializers/omniauth.rb:2:in `<module:Myapp>'
/home/adam/rails/myapp/config/initializers/omniauth.rb:1:in `<top (required)>'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `block in require'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/home/adam/rails/myapp/lib/tasks/test-user.rake:2:in `<top (required)>'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `block in load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/railties-4.0.5/lib/rails/engine.rb:641:in `block in run_tasks_blocks'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/railties-4.0.5/lib/rails/engine.rb:641:in `each'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/railties-4.0.5/lib/rails/engine.rb:641:in `run_tasks_blocks'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/railties-4.0.5/lib/rails/application.rb:244:in `run_tasks_blocks'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/railties-4.0.5/lib/rails/engine.rb:446:in `load_tasks'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/railties-4.0.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/adam/rails/myapp/Rakefile:7:in `<top (required)>'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `block in load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `block in load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `block in load'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/adam/.rvm/gems/ruby-1.9.3-p392@myapp/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:223:in `load'
-e:1:in `<main>'
(See full trace by running task with --trace)
```

**Comment by rubycop** [comment]
@aspiers I have the same error with Omniauth. But It happens when I tried register middleware when it has been already registered.
In my case I tried `load "config/initializers/omniauth.rb"` file. But it has been already present.
```ruby
> Rails.application.config.middleware
=> #<ActionDispatch::MiddlewareStack:0x0000000c18fhw3 @middlewares=[ ... OmniAuth::Builder]>

> Rails.application.config.middleware.use OmniAuth::Builder
RuntimeError: can't modify frozen Array
from /home/vagrant/.rvm/gems/ruby-2.1.2/gems/actionpack-4.0.0/lib/action_dispatch/middleware/stack.rb:112:in `push'
```

**Comment by keesbriggs** [comment]
I have the same error.

**Comment by tmilewski** [comment]
☝️ 👍 

Re-open if need be.

**Comment by atishay5395** [comment]
The error Im getting is:
RuntimeError: can't modify frozen array
                                  insert at org/jruby/RubyArray.java:959
I tried to follow the steps from : https://launchschool.com/blog/facebook-graph-api-using-omniauth-facebook-and-koala
Could anyone help me out with this?

**Comment by LucasCioffi** [comment]
I had the same problem in production but found that it goes away when setting `config.eager_load = false` in production.rb.  Is that a surprise or expected?

It's fine for the demo site I'm building, but it comes at a performance cost according to the note in `production.rb`:
```
  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
```
