### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow after update to 1.6.0

### ISSUE THREAD

**Issue by xeron** [omniauth/omniauth#888]
### Configuration

- Provider Gem: `omniauth-google-oauth2`
- Ruby Version: `2.3.3`
- Framework: `rails 5.0.1`
- Platform: `linux`/`mac`

### Expected Behavior

It should send user to google auth page. Works as expected with `omniauth (1.5.0)`.

### Actual Behavior

Rails throws an exception even before going to google auth page:

```
Started GET "/auth/google" for ::1 at 2017-02-17 18:24:19 -0800
(google) Request phase initiated.
Started GET "/auth/google" for ::1 at 2017-02-17 18:24:19 -0800
(google) Request phase initiated.
  
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
  
bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/cookies.rb:594:in `commit'
bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/cookies.rb:465:in `[]='
bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:117:in `set_cookie'
…
```
### Steps to Reproduce

`Omniauth` initializer:

```ruby
OmniAuth.config.logger = Rails.logger

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], {
    name: 'google',
    scope: 'email, profile, calendar.readonly',
    prompt: 'select_account consent'
  }
end
```

View:
```ruby
%li= link_to "Auth with Google", "/auth/google"
```

Click to `Auth with Google`.

**Comment by xeron** [comment]
May be related to https://github.com/omniauth/omniauth/pull/806?

**Comment by trammel** [comment]
I'm getting the same issue. If the sessions are stored as cookies, the extra header information blows out the cookie size past 4096 bytes.

Eg. breaking just before the controller encrypts and signs the cookie

actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:592:in `commit'
```ruby
>  options[:value]
=> {"session_id"=>"366a2afb9220613322166229c2289675", "_csrf_token"=>"AJV0U22sD9622lnDy80U22c3ZBx22amLIdMGbzWFfXA=", "omniauth.params"=>{"locale"=>"en"}, "omniauth.headers"=>{"VERSION"=>"HTTP/1.1", "HOST"=>"localhost:9292", "CONNECTION"=>"keep-alive", "CACHE_CONTROL"=>"max-age=0", "UPGRADE_INSECURE_REQUESTS"=>"1", "USER_AGENT"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36", "ACCEPT"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", "REFERER"=>"http://localhost:9292/en/users/login", "ACCEPT_ENCODING"=>"gzip, deflate, sdch, br", "ACCEPT_LANGUAGE"=>"en-GB,en-US;q=0.8,en;q=0.6", "COOKIE"=>"_xxxxxxxx_session=xxxVNTBPTkVKZkdFOE9DWGdVS2xaL0FGUk1UU01WMDk5YkZiZjRTTkYxcFFpQlJWdE1LMlQvZmV1Z2kzM1FsWjlLOXZEamh3dVhEWGdwc1hCTlIvdUxNcE5HdlRxRCt2YUNoQit0YWpyeG5TR0FpRlNYUmNhSjNSbWUzNU1DRUliRWtPSUUxV2lLeXF5dkV1emhwS3VQOUVwT241SFZBdU5vVjhJRnhWdTh6MGpvcUxRQmRoNmxHL0JUWDE4Rm9PbjFMWUlTVDFwcjRkckRMMWNxSEUxTjFUx3huQnFQZGFBbGVxdlRneXhDxVp5VFMzZHZWdVpQZUZmKzhGREdyeWNUWkE1Qnd2d0FIZ0dFODl6b2dScUVYMjlrbxRMSWw2dUYyUWpKWVhWNSs1OEl3UEJzRWlwVDc0NWUzUkR4Si9PS0VEbUYyZUphWndmak1RcG9TSjRHc1ViS0hnUGRhempxZm9USXBMZm9OWGFhNGMvbTZOM2JPSEFZazB5Y3RPZy9JRHZyKzhJSkdSTmlEblBYT3ZIbG9VYVArR1oxxW1FMG1mZ1VydmxOQjR6NDYvOTl5TVd4xnVtOFRiekxDUFcvOU5kUFNWSC96MjZhU3NwMnduNEtlSkQwckJPWTZlTHpFVlY0b0hpTmZaT0lqdCt3MU1acCs4VnJGQ0pJbHBvYXo0ZDYyb213alVSYWdVcXNOeURvNkpVdHYvbHp3UkloMkxFT1U1aS9jNXpVajVkV09zKzgxcnAxRVpIdUpHT3JXb2VqUmNpL0ZyL1FtVDVPM2pNV0NKanBvc3N1UU5aNHM4bjlXTlBVamE3T0FMOTZkTjNWYjFDbVk3STc1ZnNucy9YWkk2TE9MN2svYldZbnYrTmtCN1BLbGw1WHk0VS85MnIxWEx3MUNmaVhaanhINHBFTVVobk9KU3dIbHJUMHNJazh6Z0h6MWh4ZG52L1c2eHIxcUxZWUpiY2hmMzgwZFZDV0J6cTluVmZtMUZRWklvSVRzdlB1R0Rmd1MyVlZKM1BFS2xyQmMxYzJQMHFHT3lPam5UaDBVYWs4SFY3SUEzd2dFZGRYcFBjT0c5RTFwbjVhaEFHWVY4L01GdktGc1lxMzcvRldXcE9FeWpKZUtuUFVxL1JZTVNCZ3FJU2Q0MlBHOGg0SkxOaHFtYlBHZGlVS2ZuS1cyZmlaSnVVZE5zYlEzN25ZZVczdDRMNm41QmkwZkFsRTE5Y2h2N1paZnJCVTJrUGtLUlhNZGttOHJhM3NyRW1jVkludU5hbzNyeVgremw3S1ZSTjV0Vm9PS1hrZHVaclRadUswWndpd3pVekdlQTJ1ZXE1bkR4S1FHMHlnVGtPYXA1ZmxpNmpFTVNzcjZxYXlNa21WdTM4Tkd0MitoWklnT0FmS3JRVEtwK1doTzJ3bUgrc3JCSTVzM3BDVHJuR284WFhhTk1OOWZOKzEvYmxENmxoWE1rbnFuKzZUT1BTb3o2b0FiMVhuaGJwek0rU0xNTjdVUXZSQ3VOc0Q5QlFCR0hXWlRqYnR2R01UWXVnQnRrbUczY3M1UjRJN3hFRzFyYlIyVFBHbXdOZ05EYUpMZkZLa04zZzJhRFNyZkJFNnU3alhSd0hzcWJzcGphY3Vucm5hRTA5TDdOd3lvZVByUxgvR2U0T3ByakwvbE9oRTQrS3FpMHhPVzNRTmVVc1U4MVNaTmxMcFp1V0Jvc1FpejA2V2NLK252S0RMekVMb0RIU0VPQnFkRWsrTUlTWkI4N1NLVkJOL3lERWFCMytNdTNzbENNbktPaXJMWHV0eEhEUkV5V0VOZVE4cGRQSEFFcm14cGVsbzZ6UDR1TklLR3pEd0RVQVRXeHBRWWxyTThWeVlSMXhuNzN4MXlNem1ZaXhpSVhLT3Jnc1l0WWFpdGVKZmFrR3Z2UUlXQjFSWkI0Y3FWZnVwNnBxeE5Bc2hJSi9iV0FZeXNPclNIbnAwakZpcityN2J2cDFUYlNmcXFaMitWZlFrMGV2anllSmwzYno5ZWpXUmdxSnMrcWIzbUl3N3FHZG1FQXJiZE9mVjJ0Zm1vQ0hyaFZnNjdJR1g3Y3NEVW80Mm9RZG1IQ0htdTc2bUVXL3NkQ1NzOVZUZng2ZW52RU5LYVc3bDE5ektVSWV4QjJuZFdNWEI1Ukh2SXY2SDVIaVlKTXNsMxJ4cVk9LS1YdTFYM1Nwc3RsL1VuOGdsYVVubkxBPT0%3D--db62a4d39d33ded02c8315cb327702d54fd73537dfaf38b84b9e0774166268a0; _ga=GA1.1.64196906.1487405801; Hm_lvt_0f9ffdb05f8a34437dd4fa3af8164470=1487405803; Hm_lpvt_0f9ffdb05f8a34437dd4fa3af8164470=1487406179"}, "omniauth.origin"=>"http://localhost:9292/en/users/login", "omniauth.state"=>"60321af4099aa07c89926ccad7cac5f0b28a16c7b0e9663b"}
>>  options[:value].to_s.length
=> 3280
```

I think it's related to https://github.com/omniauth/omniauth/pull/806 also

**Comment by tmilewski** [comment]
Checking this out now. Thanks!

**Comment by tmilewski** [comment]
Reverted #806. Pushed to Rubygems at `1.6.1`. Thanks!
