### ISSUE TITLE
Are OmniAuth strategies thread safe?

### ISSUE THREAD

**Issue by jrgns** [omniauth/omniauth#940]
I've started adding `require 'rack-freeze'` to the top of my `config.ru` file to assess how thread safe my rack middleware is. The first issue I ran into was with omniauth.

### Configuration

- Provider Gem: `omniauth`
- Ruby Version: `2.4.4`
- Framework: `Rack`
- Platform: `Ubuntu`

`config.ru` file:

```ruby
require 'rack/freeze'
require 'omniauth'
use OmniAuth::Strategies::Developer
app = Proc.new do |env|
    ['200', {'Content-Type' => 'text/html'}, ['A barebones rack app.']]
end
run app
```

### Expected Behavior

A request should be handled as normal. So

```bash
$ curl localhost:9292
A barebones rack app.
```

### Actual Behavior

An exception is thrown:

```
[2018-08-11 11:15:20] INFO  WEBrick 1.3.1
[2018-08-11 11:15:20] INFO  ruby 2.4.4 (2018-03-28) [x86_64-linux-gnu]
[2018-08-11 11:15:20] INFO  WEBrick::HTTPServer#start: pid=29537 port=9292
RuntimeError: can't modify frozen OmniAuth::Strategies::Developer
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:491:in `block in dup'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:490:in `tap'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:490:in `dup'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/lint.rb:49:in `_call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/lint.rb:37:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/show_exceptions.rb:23:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/chunked.rb:54:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/content_length.rb:15:in `call'
	/home/jrgns/Code/EagerELK/threadsafe/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/usr/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
```
### Steps to Reproduce

* Ensure the omniauth and [rack-freeze](https://github.com/ioquatix/rack-freeze) gems are installed
* Create the `config.ru` file as provided above
* Run `rackup`
* Run `curl localhost:9292`

**Comment by BuonOmo** [comment]
The same issue is still present in november 2019. How can we be sure that omniauth is thread safe?

**Comment by BobbyMcWho** [comment]
I'm new to this project in general, so I don't have historical context. 

It looks like the issue is coming from here: https://github.com/omniauth/omniauth/blob/v1.9.0/lib/omniauth/strategy.rb#L494-L498

This is probably part of the reason that we see such performance issues from omniauth, seeing as the options are a hashie mash and those can be pretty bad performance wise.

**Comment by ccyrille** [comment]
Without switching from `Hashie::Mash` which is probably a separated subject, I think I found the precise fix for this particular issue. Please let me know if you find this relevant :)
