### ISSUE TITLE
rack update to 2.1.1 breaks omniauth

### ISSUE THREAD

**Issue by utkarsh2102** [omniauth/omniauth#997]
Hi there,

Whilst updating rack to 2.1.1 (from 2.0.8), there is a test failure in omniauth as below:
```
Failures:

  1) OmniAuth::Strategy#redirect uses javascript if :iframe is true
     Failure/Error: expect(response.last.body.first).to be_include('top.location.href')

     NoMethodError:
       undefined method `body' for #<Array:0x000055e164b0a1f8>
     # ./spec/omniauth/strategy_spec.rb:245:in `block (3 levels) in <top (required)>'
```

Any clue about the fix?

**Comment by BobbyMcWho** [comment]
Hi @utkarsh2102, what version of omniauth are you testing against? I believe we had resolved this.

**Comment by utkarsh2102** [comment]
Hi @bobbymarko,
This was 1.9.0.

And with the latest version, that is, 1.9.1, there is a failure, too:
```
Failures:

  1) OmniAuth::Strategy#redirect uses javascript if :iframe is true
     Failure/Error: expect(response.last).to include(expected_body)
     
       expected #<Rack::BodyProxy:0x000055c9b51b4ef8 @body=#<Rack::Response:0x000055c9b51b51c8 @status=200, @header={..."]>, @block=#<Proc:0x000055c9b51b4ea8 /usr/lib/ruby/vendor_ruby/rack/response.rb:69>, @closed=false> to include "<script type='text/javascript' charset='utf-8'>top.location.href = 'http://abc.com';</script>"
       Diff:
       @@ -1,2 +1,15 @@
       -["<script type='text/javascript' charset='utf-8'>top.location.href = 'http://abc.com';</script>"]
       +#<Rack::BodyProxy:0x000055c9b51b4ef8
       + @block=
       +  #<Proc:0x000055c9b51b4ea8 /usr/lib/ruby/vendor_ruby/rack/response.rb:69>,
       + @body=
       +  #<Rack::Response:0x000055c9b51b51c8
       +   @block=nil,
       +   @body=
       +    ["<script type='text/javascript' charset='utf-8'>top.location.href = 'http://abc.com';</script>"],
       +   @header={"Content-Length"=>"93"},
       +   @length=93,
       +   @status=200,
       +   @writer=
       +    #<Proc:0x000055c9b51b5060 /usr/lib/ruby/vendor_ruby/rack/response.rb:32 (lambda)>>,
       + @closed=false>
       
     # ./spec/omniauth/strategy_spec.rb:247:in `block (3 levels) in <top (required)>'

Finished in 0.21563 seconds (files took 0.61028 seconds to load)
180 examples, 1 failure

Failed examples:

rspec ./spec/omniauth/strategy_spec.rb:243 # OmniAuth::Strategy#redirect uses javascript if :iframe is true
```
